export const body = {
  logosTitle: 'Companies I’ve worked with',
  logos: [
    ['The JAQ Group', '1-JAQ.png'], ['FIGO', '2-FIGO.png'], ['Petra Brands', '3-Petrabrands.png'],
    ['BrandLiners', '4-Brandliners.png'], ['Dequanis', '5-DQ.png'],
  ],
  workTitle: 'Different worlds.\nOne design instinct.',
  workIntro: 'A selection of identities, campaigns and digital experiences. Take a look around.',
  servicesTitle: 'From the first idea\nto the final detail.',
  servicesIntro: 'I connect the identity, the experience and the everyday creative that keeps a brand moving.',
  services: [
    { title: 'AI images & design', description: 'Over 300 AI images created in one year. I turn visual ideas into campaign-ready imagery, with a designer’s eye for composition and brand consistency.', details: ['Nano Banana', 'GPT Image 2', 'Higgsfield'], art: 'ai', example: 'AI imagery for The JAQ Group’s fragrance email campaigns.' },
    { title: 'Brand identity', description: 'A visual language that feels like you. From the mark on the packaging to the world around the product.', details: ['Identity systems', 'Packaging', 'Brand guidelines'], art: 'bloom', example: 'Brand design across FIGO Homes and BrandLiners.' },
    { title: 'Email & marketing', description: 'Thoughtful campaigns for the moments that matter. Clear hierarchies, expressive imagery and a consistent brand voice.', details: ['Email campaigns', 'Marketing creative', 'Product storytelling'], art: 'signal', example: 'Brand email design for The JAQ Group.' },
    { title: 'Amazon & ecommerce', description: 'Make a product easy to understand and hard to overlook. A considered journey from the listing to the storefront.', details: ['Amazon listings', 'Product imagery', 'Storefront design'], art: 'cube', example: 'Amazon and product design with Petra Brands / SwiftStart.' },
    { title: 'Web & digital', description: 'Design that works beyond the frame. Digital experiences with a clear structure, considered interaction and the build to match.', details: ['UI/UX in Figma', 'WordPress', 'Shopify'], art: 'surface', example: 'Graphics and web design at BrandLiners and Dequanis.' },
  ],
  flockHint: 'I love butterflies. Hover to play. Click to make them fly.',
  artHint: 'Move to play. Tap to send a ripple.', artLabel: 'Reshape the interactive artwork',
  portraitAlt: 'Sohaib Elahi in a red ASCII portrait',
  aboutTitle: 'A designer’s eye.\nA builder’s curiosity.',
  aboutIntro: 'I’m Sohaib. I like following an idea wherever it takes me: a brand identity, an ecommerce campaign, or the code that makes a website work.',
  aboutDetail: 'I’ve moved between design and technical work because I enjoy both imagining things and figuring out how to build them. My degree in Artificial Intelligence feeds that curiosity. Lately, I’ve been thinking about a SaaS idea of my own. More on that soon.',
  skills: ['Brand identity', 'Email design', 'AI image design', 'Amazon content', 'UI/UX', 'Shopify', 'WordPress', 'Figma', 'Photoshop', 'Illustrator', 'HTML & CSS', 'Python'],
  education: 'BS Artificial Intelligence · Karachi Institute of Technology & Economics · 2021–2025',
  experienceTitle: 'Where I’ve been building',
  proofPoints: [
    { value: '300+', label: 'AI images in one year' },
    { value: '7 years', label: 'Graphic design' },
    { value: '40+', label: 'DTC brands worked with' },
    { value: '7–9', label: 'Figure brands worked with' },
  ],
  experience: [
    { company: 'The JAQ Group', role: 'Brand Email Designer', period: 'Sep 2025 — present', detail: 'Email and marketing design for fragrance brands. Remote, UK.' },
    { company: 'Petra Brands / Reely / SwiftStart', role: 'Amazon Brand Designer', period: 'Dec 2024 — Aug 2025', detail: 'Amazon listings, product design and marketing assets for international teams.' },
    { company: 'FIGO Homes', role: 'Senior Brand Designer', period: '2022 — Jan 2025', detail: 'Brand assets, packaging, Amazon listings, Shopify visuals and email creative. Remote, US.' },
    { company: 'BrandLiners', role: 'Senior Graphics & Web Designer', period: '2021 — 2024', detail: 'Private-label design, product imagery, campaigns, WordPress and Shopify websites.' },
    { company: 'Dequanis', role: 'Senior Graphic Designer', period: '2021 — 2022', detail: 'WordPress websites, marketing creative and packaging for international clients.' },
  ],
  contactTitle: 'Let’s make\nsomething resonate.',
  copyEmail: 'Copy email', copied: 'Copied', copyFailed: 'Select email to copy', back: 'Back to top',
  soundOn: 'Sound on', soundOff: 'Sound off', soundDescription: 'Optional soft interaction sounds',
} as const;
